// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMY0Wzr2C8deg8QdMWIaQ7ZD7c8QbOBOQ',
    appId: '1:673766268155:web:8bea90ba187041d92be45e',
    messagingSenderId: '673766268155',
    projectId: 'fluttervirgin-f123e',
    authDomain: 'fluttervirgin-f123e.firebaseapp.com',
    storageBucket: 'fluttervirgin-f123e.firebasestorage.app',
    measurementId: 'G-2EVFF6E5DK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUcMlJnfcvYhQRzg0yKs1DIZ7nZDPRvjU',
    appId: '1:673766268155:android:0f737cdd1a5e4e6d2be45e',
    messagingSenderId: '673766268155',
    projectId: 'fluttervirgin-f123e',
    storageBucket: 'fluttervirgin-f123e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAuWlelEy9R7R1D-jiZksMOx80WtWV23W0',
    appId: '1:673766268155:ios:95638804ae29c4bb2be45e',
    messagingSenderId: '673766268155',
    projectId: 'fluttervirgin-f123e',
    storageBucket: 'fluttervirgin-f123e.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAuWlelEy9R7R1D-jiZksMOx80WtWV23W0',
    appId: '1:673766268155:ios:95638804ae29c4bb2be45e',
    messagingSenderId: '673766268155',
    projectId: 'fluttervirgin-f123e',
    storageBucket: 'fluttervirgin-f123e.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBMY0Wzr2C8deg8QdMWIaQ7ZD7c8QbOBOQ',
    appId: '1:673766268155:web:5f4d6954c960f8d62be45e',
    messagingSenderId: '673766268155',
    projectId: 'fluttervirgin-f123e',
    authDomain: 'fluttervirgin-f123e.firebaseapp.com',
    storageBucket: 'fluttervirgin-f123e.firebasestorage.app',
    measurementId: 'G-M33NNHYZDL',
  );

}